name: blank-space
favicon: null
layout_spectrum: 0.33846793533302844
typography_spectrum: 0.5841945463325828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9079079602379352
  lightness: 0.5607320803683251
  saturation: 0.21131908567622304
  rhythmicContrast: 0.23529053525999188
purpose: []
